config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :categories
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'bookmarks#index'

  get "get_bookmarks/:category", to: "bookmarks#getBookmarksByCategory", as: "getBookmarksByCategory"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :kind
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent, class_name: "Category", optional: true, foreign_key: :category_id
    has_many :children, class_name: "Category", dependent: :destroy

    has_many :bookmarks
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :bookmarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end


  def getBookmarksByCategory
    
    
    json = {"bookmarks" => []}
    bookmarks_index = 0
    current_category = Category.where(name: params[:category]).first

    cat_parent = { current_category.name => []}
    json["bookmarks"].push(cat_parent)

    if current_category.bookmarks.count > 0
      json["bookmarks"][bookmarks_index][current_category.name].push(current_category.bookmarks.pluck(:url))
    end
    
      current_category.children.each_with_index do |child|
          arr_bookmarks = child.bookmarks.pluck(:url)
          json_bookmarks = {child.name => arr_bookmarks}
          json["bookmarks"][bookmarks_index][current_category.name].push(json_bookmarks)
      end
    

    render json: json

  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        @bookmarks = Bookmark.all
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:name, :url, :kind_id, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :private)
    end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
    @pie_kinds = Bookmark.joins(:kind).group("kinds.name").count
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/bookmarks/_bookmark.html.erb
      <tr>
        <td><%= bookmark.name %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.kind.name %></td>
        <td><%= bookmark.category.name %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, remote: true, data: { confirm: "Seguro?"}) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= form.select :kind_id, Kind.all.collect {|k| [k.name, k.id]}, id: :bookmark_kind_id, include_blank: false %>

  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]}, id: :bookmark_category_id, include_blank: false %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/create.js.erb
$("#bookmark_name").val("")
$("#bookmark_url").val("")
$("#bookmark_kind_id").val($("#bookmark_kind_id option:first").val())
$("#bookmark_category_id").val($("#bookmark_category_id option:first").val())


$("#table_bookmarks tbody").html("")
$("#table_bookmarks tbody").html("<%= j render @bookmarks %>")

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingreso de Bookmarks</h1>

<%= render 'form', bookmark: @bookmark %>

<hr>

<table class=table id="table_bookmarks">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Kind</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<br>
<br>
<br>



<h1>Bookmarks</h1>

  <tbody>
     <%= render @bookmarks %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @bookmark.kind %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class=table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th>Children</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent ? category.parent.name : "- Sin Padre -"  %></td>
        <td>
           <% category.children.each do |c| %>
              <%= c.name  %> <br>
           <% end %>
        </td>
        
        <td><%= category.private ? "Privado" : "Público" %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @category.private %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kinds</h1>


<table class=table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.name %></td>
        <td><%= link_to 'Show', kind %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind) %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Kind', new_kind_path %>

<hr>

<%= pie_chart @pie_kinds, title: "Marcadores por tipo" %>


<br>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kind.name %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">Bookmarks</a> -->
  <%= link_to " Bookmarks ", bookmarks_path, :class =>"navbar-brand"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to " Categories ", categories_path, :class =>"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to " Kinds ", kinds_path, :class =>"nav-link" %>
        <!-- <a class="nav-link" href="#">Kinds</a> -->
      </li>
    </ul>
  </div>
</nav>


    <%= yield %>
  </body>
</html>